version: "3.1"

services:
  redisstack-url-shortener:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--maxmemory 100mb --maxmemory-policy allkeys-lru

  zookeeper-url-shortener:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3500:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
    external: false
  zookeeper_data:
  zookeeper_datalog:
