{
 "title": "URL Shortener Application Dashboard",
 "description": "Dashboard for URL shortener",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request count for redirections",
   "type": "timeseries",
   "description": "Number of requests for redirections to existing URLs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "total_http_requests{route=~\"/url/.*\", route!~\"/url/short-url|/url/get-urls\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count for short URL creation",
   "type": "timeseries",
   "description": "Number of requests for short URL creation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "total_http_requests{route=\"url/short-url\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "total_http_requests{browser=\"Chrome\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}